export default function Terms() {
  return (
    <main className="min-h-screen bg-[#111827] text-[#e5e7eb] p-8 font-mono">
      <div className="max-w-3xl mx-auto space-y-6">
        <header className="border-b border-[#374151] pb-4">
          <h1 className="text-2xl font-bold tracking-tight text-[#f9fafb]">Terms of Service</h1>
          <p className="text-sm text-[#9ca3af] mt-1">SatQuery AI Application Terms</p>
        </header>
        <div className="prose prose-invert max-w-none text-sm text-[#d1d5db]">
          <p>These terms govern your use of the SatQuery AI system.</p>
          <p>This is a prototype system developed for SIH26167. Outputs generated by the system are for demonstration and informational purposes only and do not constitute authoritative legal or operational advice.</p>
          <p>By using the system, you agree not to upload classified, proprietary, or sensitive geospatial data without authorization.</p>
          <a href="/" className="text-[#60a5fa] hover:underline mt-4 inline-block">Return Home</a>
        </div>
      </div>
    </main>
  );
}
