"""Add source_type and provenance

Revision ID: ab5132d0a385
Revises: 9a59ed83378d
Create Date: 2026-09-06 09:10:13.850261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5132d0a385'
down_revision: Union[str, Sequence[str], None] = '9a59ed83378d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('provenance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'provenance')
    op.drop_column('scenes', 'source_type')
    # ### end Alembic commands ###
